### ISSUE TITLE
Error after install on Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by copostic** [mailjet/prestashop-mailjet-plugin-apiv3#106] opened 2021-03-01 15:47 UTC
Hello,

I have this error when I try to access to the configuration page of the v3.4.20:
![image](https://user-images.githubusercontent.com/17200174/109521300-74a78a80-7aad-11eb-91a0-c310561c77e7.png)

I checked for permissions but they're set to 775 on directories and 664 on files. 
Do you have any solution or an idea of something I could've made wrong ?

**Comment by garri-dev** [comment] 2021-03-16 14:11
Same problem here...

**Comment by DelecroixQuentin** [comment] 2021-04-13 08:15
Quick fix for you:
Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
`'MJ_local_path' => $this->module_access['dir'],`

**Comment by alice-elix** [comment] 2021-06-02 09:46
> 
> 
> Quick fix for you:
> Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
> `'MJ_local_path' => $this->module_access['dir'],`

I think there has been an update, because in the array there is already this line, but the problem is still there

**Comment by JimmyBWY** [comment] 2021-06-03 10:40
> Quick fix for you:
> Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
> `'MJ_local_path' => $this->module_access['dir'],`

Nice works fine

**Comment by micka-fdz** [comment] 2021-09-06 09:50
Hi. Please add this fix to next release.

**Comment by MJBGO** [comment] 2021-11-27 19:18
Same problem here. Please provide a fix :(

**Comment by oleksandr-mykhailenko** [comment] 2022-11-21 17:45
Hello, We are doing a review of current version and will check. How it works right now and do customers have a problems with that path. Thank you

**Comment by oleksandr-mykhailenko** [comment] 2022-11-28 18:26
This was fixed in previous releases

**Closed by oleksandr-mykhailenko** 2022-11-28 18:26 UTC
