### ISSUE TITLE
1.6.1.5 not compatible

### ISSUE THREAD

**Issue by dav1403** [mailjet/prestashop-mailjet-plugin-apiv3#1] opened 2016-05-10 15:07 UTC

**Comment by aneliyaB** [comment] 2016-05-11 14:36
Hello,

Could you please precise what issue you have faced with our plugin and Prestashop version 1.6.1.5? Please provide us with a print screen.

Thanks,

Aneliya

**Comment by Meh0** [comment] 2016-05-15 20:20
Hello, 

I also have an issue with Prestashop v1.6.1.5. Don't know if this is the same as the OP, but I post here anyway.
Seems like Prestashop v1.6.1.5 upgraded its version of SwiftMailer to 5.2.2 : 
https://github.com/PrestaShop/PrestaShop/pull/5214/commits

Here's an excerpt of the debug on the module tab in the admin : 

> Warning à la ligne 40 du fichier \modules\mailjet\mailjet.php
> [2] include_once(/tools/swift/Swift.php): failed to open stream: No such file or directory
> 
> Warning à la ligne 41 du fichier \modules\mailjet\mailjet.php
> [2] include_once(/tools/swift/Swift/Connection/SMTP.php): failed to open stream: No such file or directory

Indeed when browsing the Swift directory, files and folders have changed.
Should we revert our Swift folder to 1.5 until the issue is taken care of ?

Cheers.

**Comment by bramanis** [comment] 2016-09-23 07:09
My "Swift" folder under 'tools/swift' just went missing after upgrading to 1.6.1.7 and now I get the following error in the logs constantly:

mod_fcgid: stderr: PHP Warning:  include_once(): Failed opening '[..]/tools/swift/Swift/Connection/SMTP.php' for inclusion (include_path='[..]/tools/htmlpurifier/standalone:.:/usr/local/php54/share/pear') in [..]/modules/mailjet/mailjet.php on line 41, referer: [..]/index.php?controller=AdminModules&token=x

**Comment by hgonzag** [comment] 2016-10-26 17:33
I tried to install the module in Prestashop 1.6.1.7 and it don't appear in the install modules.

Best regards.

**Comment by mskochev** [comment] 2018-08-02 11:41
Closing this issue due to its age

**Closed by mskochev** 2018-08-02 11:41 UTC
